### ISSUE TITLE
Issue with monitors

### ISSUE THREAD

**Issue by HashSquatch** [dglt1/optimus-switch-sddm#2]
Hey,

Nice work on the scripts. I'm battling with a mysterious issue, where I run on dGPU mode, only my nvidia gpu is registered with xrandr. I believe the intel GPU is either powered off or not being registered at all. This is an issue as running with dGPU my eDP (Laptop screen) is not powered on however the HDMI port (External monitor) runs fine. And on intel mode, my laptop screen works and HDMI doesn't. Do you perhaps have any suggestion on what is going on?

**Comment by dglt1** [comment]
sorry for the late reply, if your still having issues please post some system info. is this on fedora?

`xrandr` would only show something like  (nvidia mode)
```
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 16384 x 16384
eDP-1-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 194mm

```
post output of these commands in code blocks so they are formatted properly. (mhwd is manjaro specific)
```
inxi -Fxxxz
mhwd -li
ls -laR /etc/X11
cat /etc/X11/xorg.conf.d
xrandr --prop
```

> (Laptop screen) is not powered on however the HDMI port (External monitor) runs fine.
without more info i cant explain the behavior.

**Comment by HashSquatch** [comment]
@dglt1 
Sorry been a bit busy. This is with Manjaro. 
# Intel active:
**inxi -Fxxxz:**
https://hastebin.com/qubukubeze.makefile
**mhwd -li:**
https://hastebin.com/ozijuvuvor.css
**ls -laR /etc/X11:**
https://hastebin.com/etazesuhej.diff
**cat /etc/X11/xorg.conf.d (I'm assuming ls):**
https://hastebin.com/udocacecex.md
**xrandr --prop:**
https://hastebin.com/elufewezoq.css
# Nvidia Active:
**inxi -Fxxxz:**
https://hastebin.com/eqabuyolox.makefile
**ls -laR /etxc/X11:**
https://hastebin.com/ijobepicip.diff
**cat /etc/X11/xorg.conf.d (I'm assuming the org file):**
https://hastebin.com/etavinojoh.makefile
**xrandr --prop:**
https://hastebin.com/tocecebene.css

Would https://wiki.archlinux.org/index.php/NVIDIA#DRM_kernel_mode_setting have something to do with it?
