### ISSUE TITLE
Super-key stopped working + Recommended Desktop Env.?

### ISSUE THREAD

**Issue by exetico** [dglt1/optimus-switch-sddm#4]
Hi,

My Super-key stopped working, mostly after running this script. I'm not quite sure why.. I've tried moving `~/.config/plasma-org.kde.plasma.desktop-appletsrc`, just to see if it changed anything - but it didn't.

However, i also noticed that my text-size changes, and the backgrounds, too (monitor 1+2).

And... New we're talking: What desktop env. is recommend for this? I'm using the default setup for Manjaro 18 with KDE :-)

**Comment by dglt1** [comment]
> My Super-key stopped working, mostly after running this script

optimus-switch should have zero effect on keybindings and/or function. possibly something else that was changed/updated around the same time?

> However, i also noticed that my text-size changes, and the backgrounds, too

if by that you mean when your using nvidia mode everything appears smaller, this is normal, i included a line in the nvidia-mode xorg configuration to set the DPI to a desired value, all you have to do is uncomment (remove the # at the beginning of the line) and set the dpi to your liking.

edit this file:
/etc/switch/nvidia/nvidia-xorg.conf

uncomment and edit as needed this line:
`Option  "DPI" "96 x 96"    #adjust this value as needed to fix scaling`

try any value you want, these for example 
```
Option  "DPI" "96 x 96" 
Option  "DPI" "120 x 120" 
Option  "DPI" "192 x 192" 
```
after you edit/save be sure to set nvidia mode again for the changes to be made effective.

> And... New we're talking: What desktop env. is recommend for this?

every de/wm has it's quirks with nvidia hardware, back when i used kde/kwin i would get screen corruption after waking from suspend which is not uncommon. gnome/mutter has a stuttering problem with nvidia drivers. deepin is where all bugs go when they leave other desktops  :smirk: .  

see where im going with this? each have their own, theres nothing wrong with using kde if thats what you prefer, theres a mutter-performance package in the aur to fix the gnome stutter issue. XFCE works great if you replace XFWM's compositor with compton, for deepin IDK, i guess you could maybe offer a blood sacrifice :rofl: .  

anyway, let me know how it goes.

EDIT: a couple hours later...... in regard to the keyboard issue, is it possible you accidentally deleted 
`/etc/X11/xorg.conf.d/00-keyboard.conf` in the process of removing the other xorg configuration files during setup?

**Comment by exetico** [comment]
Thanks for the quick answer - and sorry for the late one ;-)

What's your desktop-env at the moment?

Also, thanks for the details about DPI. I'll find my sweetspot at some point. 

Guess i'll try and reinstall Manjaro at some point, and see how it goes with the Super-key. Guess i've messed something up. It also looks like i have all the way to many active widgets, however, only a few is present on my screen. It's like KDE thinks that there is another screen or so... :-)

**Comment by dglt1** [comment]
> Thanks for the quick answer - and sorry for the late one ;-)
yw, not a problem.

> What's your desktop-env at the moment?
after kde i went to openbox and loved it, then to i3 and kinda liked it, then to awesome window manager and i havent looked back since. a desktop relying on points and clicks and a floating mess of windows feels insane to me. not sure i'll ever go back to a desktop environment but you should use what fits your needs best. for me, thats awesome-wm.

best of luck with the keyboard issue, the manjaro forum would probably know whats up given the right info.

**Comment by exetico** [comment]
Thanks for yet another reply :-)

I'm not sure what i messed up. However, after a clean install, everything works fine. And i actually ended up installing 18.1 rc8, cause it was on the flashdrive. Guess i'll wait and see. Maybe it's stable enough for me. Everything is backed up, anyway..

<hr>

If other people finds this issue, this is the steps i did - on Manjaro 18.1 RC8, just after a fresh install with free-drivers.
```
sudo pacman -Syu
mhwd -li
sudo mhwd -r pci video-linux
sudo mhwd -i pci video-nvidia-435xx
sudo pacman -S linux52-headers acpi_call-dkms xorg-xrandr xf86-video-intel git
sudo modprobe acpi_call
cd ~
git clone https://github.com/dglt1/optimus-switch-sddm
cd optimus-switch-sddm/
chmod +x install.sh 
sudo ./install.sh 
```

To get my Intel graphics working at boot, i needed to add `i915` as module in:
`sudo nano /etc/mkinitcpio.conf`
(_Replace `MODULES=""` with `MODULES="i915"`, or just add the value, if other modules is present_)

Finally build the boot image:
`sudo mkinitcpio -P`

And end with... `systemctl reboot` :-)

Now everything works smooth.
